### PR TITLE
Added macOS installation instructions

### PR DESCRIPTION
**Pull request by jvdneut**
I've added instructions for installing on macOS in a separate `dexterMML setup on macOS.md` file.

Additionally a missing `#include` was added to `nrm_full_hessian.cpp` that blocked the compiler on macOS. Strangely enough this did not cause problems on Windows.

### CODE REVIEW

**Comment by jessekps** [comment]
Thanks, possibly a different collation sequence on mac then but it is indeed a bug. 

In your installation instruction for mac I saw this: devtools::install_github("jvdneut/dexterMML")
Is that necessary? i.e. did you make further changes?

**Comment by jvdneut** [comment]
I should have mentioned that. The instruction points to my fork only because of internal use.

This should point to your original repository when merged, so `devtools::install_github("dexter-psychometrics/dexterMML")`

**Comment by jessekps** [comment]
Ah, you learn new something every day. Thanks for the work!

**Comment by jvdneut** [comment]
Thank you for merging! I have just successfully tested an install on macOS from your repository using `devtools::install_github("dexter-psychometrics/dexterMML")`

**Comment by jvdneut** [comment]
> This should point to your original repository when merged, so `devtools::install_github("dexter-psychometrics/dexterMML")`

> Ah, you learn new something every day. Thanks for the work!

To avoid confusion: this did not happen automatically, I meant that when merging this should have been done, but I force pushed this change to my fork seconds before you merged the pull request.

**Pull request merged**
